@startuml
    skinparam Style strictuml

    title Diagramme de séquence
    actor       Client      as Foo1
    control     API_Back    as Foo2
    database    BDD         as Foo4
    queue      Web_Service  as Foo3

    == Récupération du WS et envoi en base ==
        Foo2 -> Foo3 : Requete
        Foo3 --> Foo2 : Reponse JSON
        Foo2 -> Foo4 : envoi

    == Affichage de la requete ==
        Foo1 -> Foo2 : Requete
        Foo2 -> Foo4 : Requete SQL
        Foo4 --> Foo2 : Réponse
        Foo2 -> Foo1 : Affichage

@enduml